### ISSUE TITLE
Import problem vtk-mvpoly

### ISSUE THREAD

**Issue by guillermo-jimenez** [jjgreen/mvpoly#16]
Hi,

When using this library with VTK this problem arises. Imagine I was to use the mvpoly.rbf module and the vtk library in the same project. When opening the python interpreter:

```
foo@bar:~$ python
>>> import mvpoly.rbf
>>> import vtk
>>>
```

Works great. But, when importing the opposite way:

```
foo@bar:~$ python
>>> import vtk
>>> import mvpoly.rbf
QH6248 qh_lib_check: Incorrect qhull library called.  Caller uses reentrant Qhull while library is non-reentrant
QH6249 qh_lib_check: Incorrect qhull library called.  Size of qhT for caller is 8184, but for library is 2896.
QH6255 qh_lib_check: Cannot continue.  Library 'qhull 7.2.0 (2015.2 2016/01/18)' uses a dynamic qhT via qh_QHpointer (e.g., qhull_p.so)
```

Thanks and great library!

PS: I just realized it might as well be vtk's fault, as it also happens when importing `scipy.interpolate`. [Link to the issue on vtk's issue tracker](https://gitlab.kitware.com/vtk/vtk/issues/17004).

**Comment by jjgreen** [comment]
Thanks for the note on this.  It does seem to be a problem with VTK and Scipy spatial (and I think Scipy interpolate pulls that in ...) using different versions of QHull.  It is natural that VTK, being a C++ library, uses the re-entrant version, and I imagine that Scipy spatial is only using the non-reentrant version for reasons of resources ("we haven't got around to porting it to reentrant yet").

So, while I don't think there's anything I can do to MVpoly to make this go away (except drop compactly supported RBFs!), I can add a note in the MVpoly docs and leave the issue open for now in case there is any feedback from the VTK devs.

**Comment by guillermo-jimenez** [comment]
Perfect, thanks for the support and the prompt response.

Great library!
